### ISSUE TITLE
Is there an update available for this module?

### ISSUE THREAD

**Issue by monsterUser** [fulldecent/freescout-dropkick-js#2]
Hello,

this module is exactly what we could currently use - unfortunately, it seems to no longer work in the current version of FreeScout.

Is there an update available for this?

Thank you!

**Comment by fulldecent** [comment]
Much more details please. It is working for me on the latest version of FreeScout.

**Comment by fulldecent** [comment]
Also, did you initiate a chargeback on PayPal?

**Comment by monsterUser** [comment]
Good morning,

thank you for the prompt response!

Yesterday, I tried to get DropkickJS version 1.0.0 running in Freescout version 1.8.113. The module is correctly activated, and the "DropkickJS" folder is created in the Modules directory with the correct file permissions, as follows:
![Screenshot 2023-12-20 085939](https://github.com/fulldecent/freescout-dropkick-js/assets/75116606/8626806c-5cd5-4783-af57-474f32056994)

As of today, our Freescout system is running version 1.8.114.

Unfortunately, neither your original example nor the following simple example script worked for us:
![Screenshot 2023-12-20 085808](https://github.com/fulldecent/freescout-dropkick-js/assets/75116606/76f45c6f-ac7e-4871-89ac-1b08168df8e4)

It seems that the script is not being included, despite using the "Clear Cache" function, deactivating and reactivating the module, and similar actions.

No error messages appear in the logs, and there are no JavaScript errors, but unfortunately, the expected behavior is not observed.

Do you need any further information?

If the script can be made to work, we will promptly pay for it. As mentioned, we attempted to use it unsuccessfully yesterday.

Thanks again!

The following additional modules are installed:
![image](https://github.com/fulldecent/freescout-dropkick-js/assets/75116606/77d6da37-3286-4f34-995b-3e364b9151db)

**Comment by fulldecent** [comment]
Thank you, can you please share results from these troubleshooting steps?

https://github.com/fulldecent/freescout-dropkick-js/blob/main/README.md#troubleshooting

**Comment by monsterUser** [comment]
Unfortunately, it still doesn't work.

1.) 1.8.114
2.) The file permissions are correct and exactly the same as the other working modules (completely recursive).
3.) Deactivated and activated many times - also after every code change + cleared the system cache additionally.
4.) The command is integrated but not executed - even a mail() command is not executed - apparently, the script is not called at all. (???)
The file "/tmp/sidebartmp" is not created, and there is no error message.
5.) I can't find any errors in the logs either.
6.) PHP version 7.3.8

Any ideas?

**Comment by fulldecent** [comment]
Do you see warnings or notices in the logs? Or any content in there at all?

Also I see your PHP version did not have active support for 4+ years according to https://www.php.net/supported-versions.php maybe this is contributing

**Comment by monsterUser** [comment]
We are unable to retrieve warnings or notices on our current webspace, and as mentioned earlier, there are no error messages in the FreeScout log. We are giving up now and removing the module again – it's a pity that it doesn't work for us.

Thanks anyway! Merry Christmas!
